import { Metadata } from "next";
import Sidebar from "../components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ChatLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="grid lg:grid-cols-[400px_1fr] h-screen max-h-full">
      <Sidebar />
      {children}
    </main>
  );
}
