import { Metadata } from "next";
import Sidebar from "../components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ChatLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid lg:grid-cols-[300px_1fr] h-screen max-h-full">
      <nav className="bg-white">
        <Sidebar />
      </nav>
      <section className="bg-light-gray">{children}</section>
    </div>
  );
}
