import type { Metadata } from "next";
import { Noto_Sans as sans } from "next/font/google";
import "./globals.css";
import AuthContext from "@/context/AuthContext";
import Footer from "./components/Footer";

const inter = sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={inter.className}>
      <body className="flex flex-col w-full">
        <AuthContext>
          <main className="grow w-full mx-auto">{children}</main>
        </AuthContext>
        <Footer />
      </body>
    </html>
  );
}
