import type { Metadata } from "next";
import { Noto_Sans as sans } from "next/font/google";
import "./globals.css";
import AuthContext from "@/context/AuthContext";

const inter = sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={inter.className}>
      <body className="">
        <AuthContext>
          <main className="">{children}</main>
        </AuthContext>
      </body>
    </html>
  );
}
